spring.application.name=employee-network

# CognoDB Connection
spring.neo4j.uri=bolt+s://db-bebdf7ef.bravo.databases.cognodb.com:7687
spring.neo4j.authentication.username=cognodb
spring.neo4j.authentication.password=81dd4066df4a5af4256029e846a4fc78

# Server
server.port=8080
